site_name: nvim-lspconfig
site_url: https://example.com/
repo_url: https://github.com/neovim/nvim-lspconfig
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/favicon.ico
  palette:
    primary: green
    accent: green
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - sane_lists
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neovim/nvim-lspconfig
nav:
  - Home: index.md
  - Install: install.md
  - LSP:
    - Introduction: lsp/index.md
    - Languages:
      - Ada (als): lsp/als.md
      - Angular (angularls): lsp/angularls.md
      - Bash (bashls): lsp/bashls.md
      - Beancount (beancount): lsp/beancount.md
      - C like (ccls): lsp/ccls.md
      - C like (clangd): lsp/clangd.md
      - C like (sourcekit): lsp/sourcekit.md
      - Clojure (clojure_lsp): lsp/clojure_lsp.md
      - CMake (cmake): lsp/cmake.md
      - C(omnisharp): lsp/omnisharp.md
      - Crystal (crystalline): lsp/crystalline.md
      - Crystal (scry): lsp/scry.md
      - CSS (cssls): lsp/cssls.md
      - Dart (dartls): lsp/dartls.md
      - Dhall (dhall_lsp_server): lsp/dhall_lsp_server.md
      - Docker (dockerls): lsp/dockerls.md
      - DOT (dotls): lsp/dotls.md
      - Elexir (elixirls): lsp/elixirls.md
      - Elm (elmls): lsp/elmls.md
      - Erlang (erlangls): lsp/erlangls.md
      - F(fsautocomplete): lsp/fsautocomplete.md
      - Fortan (fortls): lsp/fortls.md
      - GDScript (gdscript): lsp/gdscript.md
      - Go (gopls): lsp/gopls.md
      - GraphQL (graphql): lsp/graphql.md
      - Haskell (ghcide): lsp/ghcide.md
      - Haskell (hie): lsp/hie.md
      - Haskell (hls): lsp/hls.md
      - Haxe (haxe_language_server): lsp/haxe_language_server.md
      - HTML (html): lsp/html.md
      - Java (groovyls): lsp/groovyls.md
      - Java (java_language_server): lsp/java_language_server.md
      - Java (jdtls): lsp/jdtls.md
      - JSON (jsonls): lsp/jsonls.md
      - Julia (julials): lsp/julials.md
      - Kotlin (kotlin_language_server): lsp/kotlin_language_server.md
      - Lean (lean3ls): lsp/lean3ls.md
      - Lean (leanls): lsp/leanls.md
      - Lua (sumneko_lua): lsp/sumneko_lua.md
      - Markdown (zeta_note): lsp/zeta_note.md
      - Nim (nimls): lsp/nimls.md
      - Nix (rnix): lsp/rnix.md
      - OCaml (ocamlls): lsp/ocamlls.md
      - OCaml (ocamllsp): lsp/ocamllsp.md
      - Perl (perlls): lsp/perlls.md
      - PHP (intelephense): lsp/intelephense.md
      - PHP (phpactor): lsp/phpactor.md
      - Powershell (powershell_es): lsp/powershell_es.md
      - Prisma (prismals): lsp/prismals.md
      - Puppet (puppet): lsp/puppet.md
      - PureScript (purescriptls): lsp/purescriptls.md
      - Python (jedi_language_server): lsp/jedi_language_server.md
      - Python (pyls): lsp/pyls.md
      - Python (pyls_ms): lsp/pyls_ms.md
      - Python (pylsp): lsp/pylsp.md
      - Python (pyright): lsp/pyright.md
      - Racket (racket_langserver): lsp/racket_langserver.md
      - ReScript (rescriptls): lsp/rescriptls.md
      - R (r_language_server): lsp/r_language_server.md
      - Ruby (solargraph): lsp/solargraph.md
      - Ruby (sorbet): lsp/sorbet.md
      - Rust (rls): lsp/rls.md
      - Rust (rust_analyzer): lsp/rust_analyzer.md
      - Scala (metals): lsp/metals.md
      - SQL (sqlls): lsp/sqlls.md
      - SQL (sqls): lsp/sqls.md
      - Stylelint (stylelint_lsp): lsp/stylelint_lsp.md
      - Svelte (svelte): lsp/svelte.md
      - Tailwind (tailwindcss): lsp/tailwindcss.md
      - Terraform (terraformls): lsp/terraformls.md
      - Terraform (tflint): lsp/tflint.md
      - TexLab (texlab): lsp/texlab.md
      - TypeScript (denols): lsp/denols.md
      - TypeScript (flow): lsp/flow.md
      - TypeScript (rome): lsp/rome.md
      - TypeScript (tsserver): lsp/tsserver.md
      - Vala (vala_ls): lsp/vala_ls.md
      - Verilog (svls): lsp/svls.md
      - VimScript (vimls): lsp/vimls.md
      - Vue (vuels): lsp/vuels.md
      - V (vls): lsp/vls.md
      - YAML (yamlls): lsp/yamlls.md
      - Zig (zls): lsp/zls.md
    - Misc Servers:
      - CodeQL (codeqlls): lsp/codeqlls.md
      - Diagnostics (diagnosticls): lsp/diagnosticls.md
      - Diagnostics (efm): lsp/efm.md
